version: "3.7"

services:
  ms-app:
    build:
      context: ./app/
    container_name: ms-app
    depends_on:
      - ms-mysql
    # restart: always
    environment:
      MYSQL_HOST: ms-mysql
      MYSQL_DB: pica
      MYSQL_PORT: 3306
      MYSQL_USER: pica
      MYSQL_PASSWORD: AZ92adx!!!
    ports:
      - 8080:9000
    volumes:
      - ./database_mysql:/var/lib/mysql:rw
    networks:
      - ms-network

  ms-mysql:
    build:
      context: ./docker/mysql/
    container_name: ms-mysql
    command: --default-authentication-plugin=mysql_native_password
    # restart: always
    environment:
      MYSQL_ROOT_PASSWORD: TOOR
      MYSQL_DATABASE: pica
      MYSQL_USER: pica
      MYSQL_PASSWORD: AZ92adx!!!
    ports:
      - 3306:3306
    volumes:
      - ./database_mysql:/var/lib/mysql:rw
    networks:
      - ms-network

  # db_pg:
  #   build:
  #     context: ./docker/postgres/
  #   container_name: mpd-postgres
  #   # restart: always
  #   environment:
  #     - POSTGRES_DB=customerservice
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=123456789.
  #     - PGDATA=/var/lib/postgresql/data/pgdata
  #   volumes:
  #     - ./database_postgres:/var/lib/postgresql/data
  #   ports:
  #     - 5432:5432
  #   networks:
  #     - mpd-network

volumes:
  database_mysql: {}
  # database_postgres: {}
  # database_metadata_repository: {}
  # database_datawarehouse: {}

networks:
  ms-network:
    external: true