version: "3.7"

services:
  ms-app:
    build:
      context: ./app/
    container_name: ms-app
    depends_on:
      - ms-mysql
    # restart: always
    environment:
      MYSQL_HOST: ms-mysql
      MYSQL_DB: pica
      MYSQL_PORT: 3306
      MYSQL_USER: pica
      MYSQL_PASSWORD: AZ92adx!!!
    ports:
      - 8080:9000
    volumes:
      - ./database_mysql:/var/lib/mysql:rw
    networks:
      - ms-network

  ms-mysql:
    build:
      context: ./docker/mysql/
    container_name: ms-mysql
    command: --default-authentication-plugin=mysql_native_password
    # restart: always
    environment:
      MYSQL_ROOT_PASSWORD: TOOR
      MYSQL_DATABASE: pica
      MYSQL_USER: pica
      MYSQL_PASSWORD: AZ92adx!!!
    ports:
      - 3306:3306
    volumes:
      - ./database_mysql:/var/lib/mysql:rw
    networks:
      - ms-network

volumes:
  database_mysql: {}

networks:
  ms-network:
    external: true